[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dev"

[deploy]
restartPolicyType = "ON_FAILURE"

[[volume]]
name = "config"
mountPath = "/config"
persistence = true

[[volume]]
name = "uploads"
mountPath = "/uploads"
persistence = true