services:
  web:
    dockerfile: ../Dockerfile.dev
    target: dist
    numReplicas: 1
    ports:
      - 3000:3000
      - 4200:4200
      - 5000:5000
    env:
      - key: NODE_ENV
        value: development
      - key: NEXT_PUBLIC_API_URL
        value: /api
      - key: DATABASE_URL
        value: postgresql://postiz-local:postiz-local-pwd@localhost:5432/postiz-db-local
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: JWT_SECRET
        generate: secret
      - key: SKIP_CONFIG_CHECK
        value: "true"
    volumes:
      - name: uploads
        path: /uploads
      - name: config
        path: /config

services:
  postgres:
    container_name: postiz-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postiz-local-pwd
      POSTGRES_USER: postiz-local
      POSTGRES_DB: postiz-db-local
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: postiz-redis
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  postgres-data:
  uploads:
    mountPath: /uploads
    persistent: true
  config:
    mountPath: /config
    persistent: true

scripts:
  predeploy: |
    npm install
    npm run prisma-generate
  postDeploy: |
    npm run prisma-db-push
  start: npm run railway:dev